# Generated by Django 6.0 on 2025-12-28 12:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('idle', 'IDLE'), ('processing', 'PROCESSING'), ('downloading', 'DOWNLOADING'), ('transcribing', 'TRANSCRIBING'), ('analyzing', 'ANALYZING'), ('ready', 'READY'), ('error', 'ERROR')], default='idle', max_length=20)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('style_passport', models.JSONField(blank=True, default=dict)),
                ('patterns', models.JSONField(blank=True, default=list)),
                ('grounding_sources', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('url', 'URL'), ('file', 'FILE')], max_length=10)),
                ('label', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='analysis_sources/')),
                ('file_mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='api.analysis')),
            ],
            options={
                'verbose_name': 'Источник анализа',
                'verbose_name_plural': 'Источники анализа',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripts', to='api.analysis')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScriptSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeframe', models.CharField(max_length=50)),
                ('visual', models.TextField()),
                ('audio', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='api.script')),
            ],
            options={
                'verbose_name': 'Сегмент сценария',
                'verbose_name_plural': 'Сегменты сценария',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'IMAGE'), ('video', 'VIDEO'), ('audio', 'AUDIO')], max_length=10)),
                ('status', models.CharField(choices=[('idle', 'IDLE'), ('generating_image', 'GENERATING_IMAGE'), ('generating_video', 'GENERATING_VIDEO'), ('generating_audio', 'GENERATING_AUDIO'), ('done', 'DONE'), ('error', 'ERROR')], default='idle', max_length=20)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='media/images/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='media/videos/')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='media/audio/')),
                ('external_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.scriptsegment')),
            ],
            options={
                'verbose_name': 'Медиа файл',
                'verbose_name_plural': 'Медиа файлы',
                'ordering': ['created_at'],
            },
        ),
    ]
