# Generated by Django 6.0 on 2025-12-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='kie_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mediafile',
            name='kie_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
